-- =====================================================================
-- Beulah Methodist Church: database setup
-- Paste this whole file into the Neon SQL Editor and run it ONCE on an
-- empty database. It creates every table and adds the default data.
-- (Generated by scripts/build-setup-sql.mjs; do not edit by hand.)
-- =====================================================================

BEGIN;

-- Drizzle's migration journal, so "npm run db:migrate" skips what is already applied.
CREATE SCHEMA IF NOT EXISTS "drizzle";
CREATE TABLE IF NOT EXISTS "drizzle"."__drizzle_migrations" (
  "id" SERIAL PRIMARY KEY,
  "hash" text NOT NULL,
  "created_at" bigint
);

-- Migration 0000_init
CREATE TYPE "public"."audience" AS ENUM('everyone', 'leaders', 'staff');

CREATE TYPE "public"."event_type" AS ENUM('service', 'meeting', 'rehearsal', 'special', 'outreach', 'funeral', 'wedding', 'other');

CREATE TYPE "public"."gender" AS ENUM('male', 'female');

CREATE TYPE "public"."group_role" AS ENUM('leader', 'assistant', 'member');

CREATE TYPE "public"."group_type" AS ENUM('class_meeting', 'fellowship', 'choir', 'sunday_school', 'youth', 'committee', 'ministry', 'other');

CREATE TYPE "public"."household_role" AS ENUM('head', 'spouse', 'child', 'relative', 'other');

CREATE TYPE "public"."marital_status" AS ENUM('single', 'married', 'widowed', 'divorced', 'separated');

CREATE TYPE "public"."member_status" AS ENUM('active', 'inactive', 'visitor', 'transferred', 'deceased');

CREATE TYPE "public"."membership_type" AS ENUM('full_member', 'catechumen', 'junior_member', 'adherent', 'visitor');

CREATE TYPE "public"."payment_method" AS ENUM('cash', 'mobile_money', 'bank_transfer', 'cheque', 'card', 'other');

CREATE TYPE "public"."role" AS ENUM('admin', 'pastor', 'secretary', 'treasurer', 'leader', 'member');

CREATE TABLE "account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "announcements" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"audience" "audience" DEFAULT 'everyone' NOT NULL,
	"pinned" boolean DEFAULT false NOT NULL,
	"expires_at" date,
	"created_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "attendance" (
	"event_id" integer NOT NULL,
	"member_id" integer NOT NULL,
	"recorded_by" text,
	"recorded_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "attendance_event_id_member_id_pk" PRIMARY KEY("event_id","member_id")
);

CREATE TABLE "audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text,
	"action" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" text,
	"details" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "contributions" (
	"id" serial PRIMARY KEY NOT NULL,
	"member_id" integer,
	"fund_id" integer NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"date" date NOT NULL,
	"method" "payment_method" DEFAULT 'cash' NOT NULL,
	"reference" text,
	"notes" text,
	"recorded_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "events" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"type" "event_type" DEFAULT 'service' NOT NULL,
	"description" text,
	"location" text,
	"starts_at" timestamp with time zone NOT NULL,
	"ends_at" timestamp with time zone,
	"group_id" integer,
	"headcount" integer,
	"visitor_count" integer,
	"created_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "funds" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "group_members" (
	"group_id" integer NOT NULL,
	"member_id" integer NOT NULL,
	"role" "group_role" DEFAULT 'member' NOT NULL,
	"joined_at" date DEFAULT CURRENT_DATE NOT NULL,
	CONSTRAINT "group_members_group_id_member_id_pk" PRIMARY KEY("group_id","member_id")
);

CREATE TABLE "groups" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"type" "group_type" DEFAULT 'other' NOT NULL,
	"description" text,
	"meeting_day" text,
	"meeting_time" text,
	"location" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "households" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"address" text,
	"city" text,
	"phone" text,
	"email" text,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "members" (
	"id" serial PRIMARY KEY NOT NULL,
	"household_id" integer,
	"household_role" "household_role",
	"title" text,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"other_names" text,
	"gender" "gender",
	"date_of_birth" date,
	"marital_status" "marital_status",
	"phone" text,
	"alt_phone" text,
	"email" text,
	"address" text,
	"hometown" text,
	"occupation" text,
	"status" "member_status" DEFAULT 'active' NOT NULL,
	"membership_type" "membership_type" DEFAULT 'full_member' NOT NULL,
	"membership_date" date,
	"baptism_date" date,
	"confirmation_date" date,
	"marriage_date" date,
	"emergency_contact" text,
	"photo_url" text,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "messages" (
	"id" serial PRIMARY KEY NOT NULL,
	"subject" text NOT NULL,
	"body" text NOT NULL,
	"audience_label" text NOT NULL,
	"recipient_count" integer NOT NULL,
	"sent_count" integer DEFAULT 0 NOT NULL,
	"status" text NOT NULL,
	"sent_by" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "pledges" (
	"id" serial PRIMARY KEY NOT NULL,
	"member_id" integer NOT NULL,
	"fund_id" integer NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"start_date" date NOT NULL,
	"end_date" date NOT NULL,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "session_token_unique" UNIQUE("token")
);

CREATE TABLE "settings" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);

CREATE TABLE "user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"role" "role" DEFAULT 'member' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"member_id" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "user_email_unique" UNIQUE("email")
);

CREATE TABLE "verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

ALTER TABLE "account" ADD CONSTRAINT "account_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "announcements" ADD CONSTRAINT "announcements_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "attendance" ADD CONSTRAINT "attendance_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "attendance" ADD CONSTRAINT "attendance_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "attendance" ADD CONSTRAINT "attendance_recorded_by_user_id_fk" FOREIGN KEY ("recorded_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "contributions" ADD CONSTRAINT "contributions_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "contributions" ADD CONSTRAINT "contributions_fund_id_funds_id_fk" FOREIGN KEY ("fund_id") REFERENCES "public"."funds"("id") ON DELETE restrict ON UPDATE no action;

ALTER TABLE "contributions" ADD CONSTRAINT "contributions_recorded_by_user_id_fk" FOREIGN KEY ("recorded_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "events" ADD CONSTRAINT "events_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "events" ADD CONSTRAINT "events_created_by_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "group_members" ADD CONSTRAINT "group_members_group_id_groups_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."groups"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "group_members" ADD CONSTRAINT "group_members_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "members" ADD CONSTRAINT "members_household_id_households_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."households"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "messages" ADD CONSTRAINT "messages_sent_by_user_id_fk" FOREIGN KEY ("sent_by") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;

ALTER TABLE "pledges" ADD CONSTRAINT "pledges_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "pledges" ADD CONSTRAINT "pledges_fund_id_funds_id_fk" FOREIGN KEY ("fund_id") REFERENCES "public"."funds"("id") ON DELETE restrict ON UPDATE no action;

ALTER TABLE "session" ADD CONSTRAINT "session_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;

ALTER TABLE "user" ADD CONSTRAINT "user_member_id_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "public"."members"("id") ON DELETE set null ON UPDATE no action;

CREATE INDEX "account_user_idx" ON "account" USING btree ("user_id");

CREATE INDEX "attendance_member_idx" ON "attendance" USING btree ("member_id");

CREATE INDEX "audit_created_idx" ON "audit_log" USING btree ("created_at");

CREATE INDEX "contributions_date_idx" ON "contributions" USING btree ("date");

CREATE INDEX "contributions_member_idx" ON "contributions" USING btree ("member_id");

CREATE INDEX "contributions_fund_idx" ON "contributions" USING btree ("fund_id");

CREATE INDEX "events_starts_idx" ON "events" USING btree ("starts_at");

CREATE UNIQUE INDEX "funds_name_idx" ON "funds" USING btree ("name");

CREATE INDEX "group_members_member_idx" ON "group_members" USING btree ("member_id");

CREATE INDEX "members_name_idx" ON "members" USING btree ("last_name","first_name");

CREATE INDEX "members_household_idx" ON "members" USING btree ("household_id");

CREATE INDEX "members_status_idx" ON "members" USING btree ("status");

CREATE INDEX "session_user_idx" ON "session" USING btree ("user_id");

CREATE INDEX "verification_identifier_idx" ON "verification" USING btree ("identifier");

INSERT INTO "drizzle"."__drizzle_migrations" ("hash", "created_at") VALUES ('49be556d5d04d59bcdd41d21ada3d9ff63837498b213188dfb32114433e2cbbb', 1790534695434);

-- ---------------------------------------------------------------------
-- Default data
-- ---------------------------------------------------------------------

-- Church settings (all editable later under Admin > Settings)
INSERT INTO "settings" ("key", "value") VALUES
  ('churchName', 'Beulah Methodist Church'),
  ('shortName', 'Beulah Methodist'),
  ('currency', 'GHS'),
  ('timezone', 'Africa/Accra'),
  ('locale', 'en-GB'),
  ('address', ''),
  ('phone', ''),
  ('email', ''),
  ('website', '')
ON CONFLICT ("key") DO NOTHING;

-- Giving funds
INSERT INTO "funds" ("name", "description") VALUES
  ('Tithe', 'Tithes (one tenth)'),
  ('Sunday Offering', 'General offering at services'),
  ('Thanksgiving', 'Thanksgiving offerings'),
  ('Harvest', 'Annual harvest thanksgiving'),
  ('Building Fund', 'Church building and projects'),
  ('Welfare', 'Support for members in need'),
  ('Missions & Evangelism', 'Outreach and mission work'),
  ('Class Dues', 'Class meeting dues and contributions')
ON CONFLICT ("name") DO NOTHING;

-- Starter groups (rename or delete as needed)
INSERT INTO "groups" ("name", "type", "meeting_day", "meeting_time", "location") VALUES
  ('Singing Band', 'choir', 'Thursday', '17:00', 'Church premises'),
  ('Church Choir', 'choir', 'Saturday', '16:00', 'Church premises'),
  ('Women''s Fellowship', 'fellowship', 'Friday', '17:30', 'Church premises'),
  ('Men''s Fellowship', 'fellowship', 'Friday', '17:30', 'Church premises'),
  ('Youth Fellowship', 'youth', 'Saturday', '15:00', 'Church premises'),
  ('Girls'' Fellowship', 'youth', 'Saturday', '15:00', 'Church premises'),
  ('Boys'' Brigade', 'youth', 'Saturday', '09:00', 'Church premises'),
  ('Sunday School', 'sunday_school', 'Sunday', '08:00', 'Church premises'),
  ('Guild', 'fellowship', 'Wednesday', '17:30', 'Church premises'),
  ('Leaders'' Meeting', 'committee', NULL, NULL, 'Church office');

-- Welcome notice
INSERT INTO "announcements" ("title", "body", "pinned") VALUES
  ('Welcome to the Beulah Methodist Church app',
   'Members can sign in with their Google account to see church announcements, upcoming events and their own giving history. Install it on your phone from the menu with "Install app".',
   true);

COMMIT;
